In [4]:
import numpy as np
np.random.seed(0)
# Number of items sold
sales_amt=np.random.randint(5,50,size=(7,5))
sales_amt

array([[49,  5,  8,  8, 44],
       [14, 24, 26, 41, 28],
       [11, 29, 29, 17,  6],
       [43, 44, 28, 29, 22],
       [42, 30, 18, 13, 14],
       [25, 21, 10, 20,  5],
       [23, 40, 29, 34, 24]])

### See as dataframe

In [6]:
import pandas as pd
weekly_sales=pd.DataFrame(sales_amt,index=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],columns=["Book","Pen","Pencil","Eraser","Scale"])
weekly_sales

Book  Pen  Pencil  Eraser  Scale
Mon    49    5       8       8     44
Tue    14   24      26      41     28
Wed    11   29      29      17      6
Thu    43   44      28      29     22
Fri    42   30      18      13     14
Sat    25   21      10      20      5
Sun    23   40      29      34     24

In [8]:
# Create prices array
prices=np.array([30,10,5,5,12])
prices

array([30, 10,  5,  5, 12])

In [11]:
prices_df=pd.DataFrame(prices.reshape(1,5),index=["Prices"],columns=["Book","Pen","Pencil","Eraser","Scale"])
prices_df

Book  Pen  Pencil  Eraser  Scale
Prices    30   10       5       5     12

In [12]:
total_sales=prices.dot(sales_amt)

ValueError: shapes (5,) and (7,5) not aligned: 5 (dim 0) != 7 (dim 0)

In [26]:
prices,prices.shape


(array([30, 10,  5,  5, 12]), (5,))

In [29]:
sales_amt,sales_amt.shape

(array([[49,  5,  8,  8, 44],
        [14, 24, 26, 41, 28],
        [11, 29, 29, 17,  6],
        [43, 44, 28, 29, 22],
        [42, 30, 18, 13, 14],
        [25, 21, 10, 20,  5],
        [23, 40, 29, 34, 24]]),
 (7, 5))

In [35]:
#prices as array
total_sales=sales_amt.dot(prices)

In [36]:
total_sales

array([2128, 1331,  922, 2279, 1883, 1170, 1693])

In [32]:
#Create daily sales as dataframe
prices_df.shape,weekly_sales.shape

((1, 5), (7, 6))

In [19]:
daily_sales=prices_df.dot(weekly_sales.T)

In [20]:
daily_sales

Mon   Tue  Wed   Thu   Fri   Sat   Sun
Prices  2128  1331  922  2279  1883  1170  1693

In [21]:
weekly_sales

Book  Pen  Pencil  Eraser  Scale
Mon    49    5       8       8     44
Tue    14   24      26      41     28
Wed    11   29      29      17      6
Thu    43   44      28      29     22
Fri    42   30      18      13     14
Sat    25   21      10      20      5
Sun    23   40      29      34     24

In [22]:
weekly_sales["Total(Rs)"]=daily_sales.T
weekly_sales

Book  Pen  Pencil  Eraser  Scale  Total(Rs)
Mon    49    5       8       8     44       2128
Tue    14   24      26      41     28       1331
Wed    11   29      29      17      6        922
Thu    43   44      28      29     22       2279
Fri    42   30      18      13     14       1883
Sat    25   21      10      20      5       1170
Sun    23   40      29      34     24       1693

In [23]:
prices_df

Book  Pen  Pencil  Eraser  Scale
Prices    30   10       5       5     12

In [54]:
bookstore=pd.read_csv("StoreSales.csv",header=2,index_col=False)

bookstore

Unnamed: 0  Book  Pen  Pencil  Eraser  Scale  Total(Rs)
0     Monday    12   20      10       2      5      680.0
1    Tuesday    15   23      12       5     10      885.0
2  Wednesday    20   22      25       5     12     1090.0
3   Thursday     6   32      60      12     34     1295.0
4     Friday    12   12      32      13      6     1500.0
5   Saturday    10   54      12      17     15     1705.0
6     Sunday    25   57      66      20     25     1910.0
7        NaN   NaN  NaN     NaN     NaN    NaN        NaN
8      Price  Book  Pen  Pencil  Eraser  Scale        NaN
9        NaN    30   10       5       5     12        NaN

In [58]:
bookstore.dropna(inplace=True)
bookstore

Unnamed: 0 Book Pen Pencil Eraser Scale  Total(Rs)
0     Monday   12  20     10      2     5      680.0
1    Tuesday   15  23     12      5    10      885.0
2  Wednesday   20  22     25      5    12     1090.0
3   Thursday    6  32     60     12    34     1295.0
4     Friday   12  12     32     13     6     1500.0
5   Saturday   10  54     12     17    15     1705.0
6     Sunday   25  57     66     20    25     1910.0