In [2]:
import numpy as np

## DATA TYPE AND ATTRIBUTES

#NUMPY MAIN DATA TYPE-->N Dimension ARRAY

In [3]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)


numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
a1.ndim

1

In [7]:
a2=np.array([[1,2,3],[2,3,4]])
a2

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
type(a2)

numpy.ndarray

In [9]:
a2.shape

(2, 3)

In [10]:
a2.ndim

2

In [11]:
a3=np.array([[[1,2,3],[3,4,5]],[[2,5,6],[7,8,9]],[[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[2, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [12]:
a3.ndim


3

In [13]:
a3.shape

(3, 2, 3)

In [14]:
type(a3)

numpy.ndarray

In [15]:
a3.size

18

#create dataframe from array using pandas

In [16]:
import pandas as pd

In [17]:
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  2  3  4

## Creating Array

In [18]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
start_stop=np.arange(0,10,2)
start_stop

array([0, 2, 4, 6, 8])

In [20]:
zeros=np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
rand1=np.random.randint(0,10,size=(3,5))
rand1

array([[8, 3, 5, 4, 6],
       [7, 0, 9, 3, 7],
       [6, 6, 3, 2, 1]])

In [22]:
rand2=np.random.random((5,3))
rand2

array([[0.80601245, 0.47649959, 0.93154797],
       [0.36426051, 0.94518115, 0.03379261],
       [0.62677321, 0.50081038, 0.12522044],
       [0.51314535, 0.5905279 , 0.89259052],
       [0.32996783, 0.46042585, 0.87774301]])

In [23]:
rand3=np.random.rand(3,5)
rand3

array([[0.6365303 , 0.99332649, 0.19074054, 0.84163624, 0.42393854],
       [0.81271868, 0.97765917, 0.91639733, 0.15175183, 0.80229392],
       [0.44578619, 0.95545703, 0.65840382, 0.57836244, 0.3506431 ]])

In [24]:
rand3

array([[0.6365303 , 0.99332649, 0.19074054, 0.84163624, 0.42393854],
       [0.81271868, 0.97765917, 0.91639733, 0.15175183, 0.80229392],
       [0.44578619, 0.95545703, 0.65840382, 0.57836244, 0.3506431 ]])

In [25]:
np.random.seed(seed=88)
rand2

array([[0.80601245, 0.47649959, 0.93154797],
       [0.36426051, 0.94518115, 0.03379261],
       [0.62677321, 0.50081038, 0.12522044],
       [0.51314535, 0.5905279 , 0.89259052],
       [0.32996783, 0.46042585, 0.87774301]])

## Viewing array and matrix

In [26]:
np.unique(rand3)

array([0.15175183, 0.19074054, 0.3506431 , 0.42393854, 0.44578619,
       0.57836244, 0.6365303 , 0.65840382, 0.80229392, 0.81271868,
       0.84163624, 0.91639733, 0.95545703, 0.97765917, 0.99332649])

In [27]:
a3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[2, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [28]:
np.unique(a3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a3.shape

(3, 2, 3)

In [30]:
a3[:,:,:1]

array([[[1],
        [3]],

       [[2],
        [7]],

       [[4],
        [7]]])

In [31]:
a3[:1,:,:]

array([[[1, 2, 3],
        [3, 4, 5]]])

In [32]:
a3[:,:1,:]

array([[[1, 2, 3]],

       [[2, 5, 6]],

       [[4, 5, 6]]])

In [33]:
a3[0]

array([[1, 2, 3],
       [3, 4, 5]])

In [34]:
a3[0,1]

array([3, 4, 5])

## Manipulating Arrays

#### Arithematic calculations

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
a1+a2

array([[2, 4, 6],
       [3, 5, 7]])

In [38]:
a2+a1

array([[2, 4, 6],
       [3, 5, 7]])

In [39]:
a1-a2

array([[ 0,  0,  0],
       [-1, -1, -1]])

In [40]:
a1*a2

array([[ 1,  4,  9],
       [ 2,  6, 12]])

In [41]:
a1*22

array([22, 44, 66])

In [42]:
a2//2

array([[0, 1, 1],
       [1, 1, 2]])

In [43]:
a2%2

array([[1, 0, 1],
       [0, 1, 0]])

In [44]:
a2/2


array([[0.5, 1. , 1.5],
       [1. , 1.5, 2. ]])

In [45]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [0.69314718, 1.09861229, 1.38629436]])

#### Aggregation

In [46]:
a1

array([1, 2, 3])

In [47]:
sum(a1)

6

In [48]:
np.sum(a1)

6

##Both are same but 1st is python sum and second is numpy sum so use recpectively as numpy takes less time

In [49]:
%timeit sum(a1) #python datatype



582 ns ± 1.08 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [50]:
%timeit np.sum(a1) #numpy datatype

1.97 µs ± 14.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [51]:
np.mean(a1)

2.0

In [52]:
np.std(a1) #std=sqrt(var)

0.816496580927726

In [53]:
np.var(a1) #mean diff avg

0.6666666666666666

In [54]:
np.min(a1)

1

#### Reshape and transpose

In [55]:
a2.shape

(2, 3)

In [56]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]])

In [57]:
a2*a3 #without reshaping cant multiply

array([[[ 1,  4,  9],
        [ 6, 12, 20]],

       [[ 2, 10, 18],
        [14, 24, 36]],

       [[ 4, 10, 18],
        [14, 24, 36]]])

In [58]:
a2_t=a2.T #Transpose

In [59]:
a2_t.shape

(3, 2)

## Dot product

### Elementwise multiplication `(5*3) * (5*3)`

In [60]:
np.random.seed(seed=3)
mat1=np.random.randint(10,size=(3,5))
mat2=np.random.randint(10,size=(3,5))

In [61]:
mat1

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4]])

In [62]:
mat2

array([[7, 8, 1, 6, 2],
       [2, 1, 3, 5, 8],
       [1, 8, 7, 8, 1]])

In [63]:
mat1*mat2

array([[56, 72,  3, 48, 16],
       [ 0,  5,  9, 45, 72],
       [ 5, 56, 42,  0,  4]])

### Dot product `(5*3) * (3*5)`

In [65]:
np.dot(mat1,mat2)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [66]:
mat2.T

array([[7, 2, 1],
       [8, 1, 8],
       [1, 3, 7],
       [6, 5, 8],
       [2, 8, 1]])

In [67]:
mat1*mat2

array([[56, 72,  3, 48, 16],
       [ 0,  5,  9, 45, 72],
       [ 5, 56, 42,  0,  4]])

## Comparision

In [68]:
a1

array([1, 2, 3])

In [69]:
a2

array([[1, 2, 3],
       [2, 3, 4]])

In [70]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [71]:
a1>1

array([False,  True,  True])

In [73]:
a1>=1

array([ True,  True,  True])

In [74]:
a1==1

array([ True, False, False])

## Sorting Arrays

In [75]:
a1

array([1, 2, 3])

In [78]:
rand1

array([[8, 3, 5, 4, 6],
       [7, 0, 9, 3, 7],
       [6, 6, 3, 2, 1]])

In [80]:
np.sort(rand1) #by numbers in row

array([[3, 4, 5, 6, 8],
       [0, 3, 7, 7, 9],
       [1, 2, 3, 6, 6]])

In [81]:
np.argsort(rand1) #by index

array([[1, 3, 2, 4, 0],
       [1, 3, 0, 4, 2],
       [4, 3, 2, 0, 1]])

In [84]:
np.sort(rand1,axis=1) #by row

array([[3, 4, 5, 6, 8],
       [0, 3, 7, 7, 9],
       [1, 2, 3, 6, 6]])